[project]
name = "roast-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anyio>=4.10.0",
    "claude-code-sdk>=0.0.19",
    "prefect>=3.4.12",
]

[dependency-groups]
dev = [
    "ruff>=0.12.8",
]
