name: Deploy Prefect Flow

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Deploy Prefect flow
      if: github.ref == 'refs/heads/main'
      run: |
        uv run prefect deploy --name roast-desertaxle
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}